[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 600
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 5
startCommand = "docker-compose -f docker-compose.railway.yml up"

[variables]
JWT_SECRET = "nEUzgqgNR7VqPiZecqKKNhfdrm72l8xH6AQp+hnMU6eon2y9UugBlL3+1qPWmoGK6v/O2lLoUZBqO0TfNWKb4Q=="
STORAGE_PROVIDER = "local"
IS_GENERAL = "true"
DISABLE_REGISTRATION = "true"
