[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
JWT_SECRET = "znuRXfckJe/T7OCVEGQgoB2xo+iGRzYAtc4D7u7JN07jBccQRNs3M8ADoUehangouXJqv/famV5R2sGlIUP0Lw=="
STORAGE_PROVIDER = "local"
IS_GENERAL = "true"
DISABLE_REGISTRATION = "true"
