[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
JWT_SECRET = "znuRXfckJe/T7OCVEGQgoB2xo+iGRzYAtc4D7u7JN07jBccQRNs3M8ADoUehangouXJqv/famV5R2sGlIUP0Lw=="
IS_GENERAL = "true"
STORAGE_PROVIDER = "local"
UPLOAD_DIRECTORY = "/uploads"
NEXT_PUBLIC_UPLOAD_DIRECTORY = "/uploads"
MAIN_URL = "${{RAILWAY_PUBLIC_DOMAIN}}"
FRONTEND_URL = "${{RAILWAY_PUBLIC_DOMAIN}}"
NEXT_PUBLIC_BACKEND_URL = "${{RAILWAY_PUBLIC_DOMAIN}}/api"
BACKEND_INTERNAL_URL = "http://localhost:3000"
PORT = "5000"
DISABLE_REGISTRATION = "false"
